# Generated by Django 5.0.1 on 2024-03-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_category_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["parent__id", "position"],
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی ها",
            },
        ),
    ]
